# Generated by Django 3.2.6 on 2021-08-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentacademics',
            old_name='roll_no',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='bio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='chemistry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='math',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='physics',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
